# Generated by Django 4.2.7 on 2024-01-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_candidat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='cv',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
